// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaG55uGU9C6RGJM2hXMqMsy6WfyLUf-NA',
    appId: '1:717800633688:web:40f5b7a9af21ef159c212d',
    messagingSenderId: '717800633688',
    projectId: 'cop-34068',
    authDomain: 'cop-34068.firebaseapp.com',
    storageBucket: 'cop-34068.appspot.com',
    measurementId: 'G-N68TZ6885V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF1c_dKWqnxYm6GEfmdHVoQwoC9cU8t5U',
    appId: '1:717800633688:android:627cf0fc247afd3a9c212d',
    messagingSenderId: '717800633688',
    projectId: 'cop-34068',
    storageBucket: 'cop-34068.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT4M2f-s5BMHBkNv82y_9egEdDcCAyfZA',
    appId: '1:717800633688:ios:17a730dc4d3beb909c212d',
    messagingSenderId: '717800633688',
    projectId: 'cop-34068',
    storageBucket: 'cop-34068.appspot.com',
    iosClientId: '717800633688-1k8frv3onegui0cue97r17ng1r21jp3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT4M2f-s5BMHBkNv82y_9egEdDcCAyfZA',
    appId: '1:717800633688:ios:17a730dc4d3beb909c212d',
    messagingSenderId: '717800633688',
    projectId: 'cop-34068',
    storageBucket: 'cop-34068.appspot.com',
    iosClientId: '717800633688-1k8frv3onegui0cue97r17ng1r21jp3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
